#!/usr/bin/env bash
# To configure domain zone for subdomain www on load balancer

domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

sub_domain=('www' 'web-01' 'web-02' 'lb-01')

if [ "$#" == 1 ]
then
  domain_info "$1" "${sub_domain[0]}"
  domain_info "$1" "${sub_domain[3]}"
  domain_info "$1" "${sub_domain[1]}"
  domain_info "$1" "${sub_dormain[2]}"
elif [ "$#" == 2 ]
then
  domain_info "$1" "$2"
fi
