#!/usr/bin/env bash
# redirecting to another page

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# Allow incoming HTTP
sudo ufw allow 'Nginx HTTP'

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Server configuration
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

#Restart the server
sudo service nginx restart
