#!/usr/bin/env bash
# redirecting to another page

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

#allow firewall
ufw allow 'Nginx HTTP'

# on GET request
echo 'Hello World!' > /var/www/html/index.html-debian.html

# Server configuration
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.google.com;' /etc/nginx/sites-available/default

#Restart the server
sudo system nginx restart
