#!/usr/bin/env bash
# redirecting to another page

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# To create a custom 404 HTML page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

# Server configuration
sudo printf "server {
	listen 80 default_server;
	server_name _;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404 > /dev/null

# Create a symbolic link to enable the server block
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

#Reload the server
sudo service nginx reload
