#!/usr/bin/env bash
# Script that display I am invincible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM

str=1
while [ $str ]; do
	echo "To infinity and beyond"
	sleep 2
done
