#!/usr/bin/env bash
# bash script that configure ufw

#install ufw
sudo apt-get -y update
sudo apt-get -y install ufw

#traffic
sudo ufw default deny incoming

#allow hosts
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

#ufw enable
sudo ufw enable 
